# Generated by Django 2.0.1 on 2018-02-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Achievement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='authority',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='licenseNumber',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
