# Generated by Django 2.0.1 on 2018-02-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('role', models.CharField(max_length=1000)),
                ('projectLogo', models.CharField(max_length=1000)),
            ],
        ),
    ]
