# Generated by Django 2.0.1 on 2018-02-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_projects_refrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='type',
            field=models.CharField(default='Genre', max_length=100),
            preserve_default=False,
        ),
    ]
